language: objective-c
os: osx
osx_image: xcode8.2

cache:
  cocoapods: true
  directories:
  - Carthage

xcode_project: MoyaObjectMapper.xcodeproj 

xcode_scheme:
  - MoyaObjectMapper
  - RxMoyaObjectMapper
  - ReactiveMoyaObjectMapper

env:
  - CACHE_NAME=iOS       PLATFORM=iOS
  - CACHE_NAME=macOS     PLATFORM=macOS
  - CACHE_NAME=tvOS      PLATFORM=tvOS
  - CACHE_NAME=watchOS   PLATFORM=watchOS

before_install:
  - brew update
  # Cocoapod
  - brew install cocoapods || brew upgrade cocoapods
  # SwiftLint
  - brew install swiftlint || brew upgrade swiftlint
  # Carthage tools
  - brew install carthage || brew upgrade carthage
  - curl -L -O https://github.com/YPlan/CartfileDiff/releases/download/0.1/CartfileDiff.pkg
  - sudo installer -pkg CartfileDiff.pkg -target /
  # xcpretty
  - gem install xcpretty
  # danger
  - gem install danger danger-swiftlint

before_script:
  - export RUN_TESTS="YES"
  - export POD_LINT="NO"
  - export SCHEME="${TRAVIS_XCODE_SCHEME}-${PLATFORM}"

  - case "${PLATFORM}" in
      "iOS")
        export SDK="iphonesimulator10.2";
        export DESTINATION="platform=iOS Simulator,OS=10.1,name=iPhone 7";
        ;;
      "macOS")
        export SDK="macosx10.12";
        export DESTINATION="platform=OS X,arch=x86_64";
        ;;
      "tvOS")
        export SDK="appletvsimulator10.1";
        export DESTINATION="OS=10.0,name=Apple TV 1080p";
        ;;
      "watchOS")
        export SDK="watchsimulator3.1";
        export DESTINATION="platform=watchOS Simulator,OS=3.1,name=Apple Watch Series 2 - 42mm";
        export RUN_TESTS="NO";
        ;;
    esac

  - if [ ${SCHEME} == "MoyaObjectMapper-iOS" ]; then
      export POD_LINT="YES";
    fi

  # bootstrap the dependencies for the project
  # you can remove if you don't have dependencies
  - PLATFORM=${PLATFORM} ./scripts/bootstrap-if-needed

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  
  - xcodebuild clean -project "${TRAVIS_XCODE_PROJECT}" -scheme "${SCHEME}" | xcpretty

  # Build Framework in Debug and Run Tests if specified
  - echo "BUILD FOR DEBUG"
  - if [ ${RUN_TESTS} == "YES" ]; then
      xcodebuild -project "${TRAVIS_XCODE_PROJECT}" -scheme "${SCHEME}" -sdk "${SDK}" -destination "${DESTINATION}" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
    else
      xcodebuild -project "${TRAVIS_XCODE_PROJECT}" -scheme "${SCHEME}" -sdk "${SDK}" -destination "${DESTINATION}" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

  - xcodebuild clean -project "$TRAVIS_XCODE_PROJECT" -scheme "$SCHEME" | xcpretty

  # Build Framework in Release and Run Tests if specified
  - echo "BUILD FOR RELEASE"
  - if [ ${RUN_TESTS} == "YES" ]; then
      xcodebuild -project "${TRAVIS_XCODE_PROJECT}" -scheme "${SCHEME}" -sdk "${SDK}" -destination "${DESTINATION}" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
    else
      xcodebuild -project "${TRAVIS_XCODE_PROJECT}" -scheme "${SCHEME}" -sdk "${SDK}" -destination "${DESTINATION}" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

  # Build Example in Debug if specified
  - if [ ${SDK} == "iOS" ]; then
      cd Demo;
      pod install;
      xcodebuild -project "Demo.xcworkspace" -scheme "Demo" -sdk "${SDK}" -destination "${DESTINATION}" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
      cd ..;
    fi

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ] && [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
      pod repo update > /dev/null;
      travis_wait 60 pod lib lint --allow-warnings;
    fi

after_success:
  - danger
  - bash <(curl -s https://codecov.io/bash)

#before_deploy:
#  - carthage build --no-skip-current
#  - carthage archive $FRAMEWORK_NAME
